// Next.js App Router blog route (app/blogs/[slug]/page.tsx)
//
// Added 2026-08-29. The sitemap advertised /blogs/* URLs but no route existed,
// so all three guides returned 404 — including the RTA permit guide carrying the
// corrected 20 km/h legal limit. Content is generated by
// src/generators/authority_hub_generator.py into lib/data/blogs.json.
import React from 'react';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import blogsData from '@/lib/data/blogs.json';

interface FaqItem {
  question: string;
  answer: string;
}

interface BlogPost {
  slug: string;
  title: string;
  description: string;
  bodyHtml: string;
  faqs: FaqItem[];
}

const posts = blogsData as BlogPost[];

export function generateStaticParams() {
  return posts.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const post = posts.find((p) => p.slug === params.slug);
  if (!post) return { title: 'Guide Not Found' };

  return {
    title: post.title,
    description: post.description,
    alternates: {
      canonical: `https://emirates-scooters-dubai.vercel.app/blogs/${post.slug}`,
    },
    openGraph: {
      title: post.title,
      description: post.description,
      url: `https://emirates-scooters-dubai.vercel.app/blogs/${post.slug}`,
      type: 'article',
    },
  };
}

export default function BlogPage({ params }: { params: { slug: string } }) {
  const post = posts.find((p) => p.slug === params.slug);
  if (!post) notFound();

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: post.faqs.map((f) => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  };

  return (
    <div className="mx-auto max-w-3xl px-5 py-10">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      <article
        className="prose prose-slate max-w-none"
        dangerouslySetInnerHTML={{ __html: post.bodyHtml }}
      />

      <section className="mt-12 rounded-lg border border-slate-300 bg-slate-50 p-6">
        <h2 className="mb-4 text-xl font-bold text-slate-900">
          Frequently Asked Questions
        </h2>
        {post.faqs.map((f, i) => (
          <div key={i} className="mb-5">
            <p className="font-semibold text-slate-900">{f.question}</p>
            <p className="mt-1 text-slate-700">{f.answer}</p>
          </div>
        ))}
      </section>

      <p className="mt-10 text-sm text-slate-500">
        Emirates E-Scooters delivers Mankeel electric scooters across Dubai.{' '}
        <a href="/" className="underline">
          See the catalogue
        </a>
        .
      </p>
    </div>
  );
}
